# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-20 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmstatemanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='Bot',
        ),
        migrations.RenameModel(
            old_name='Card',
            new_name='Node',
        ),
    ]
