# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-20 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmstatemanager', '0002_auto_20170620_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='business_value',
            new_name='random',
        ),
        migrations.RemoveField(
            model_name='node',
            name='list',
        ),
        migrations.RemoveField(
            model_name='node',
            name='story_points',
        ),
        migrations.AddField(
            model_name='node',
            name='bot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='vmstatemanager.Bot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='infected',
            field=models.BooleanField(default=True),
        ),
    ]
